name: "Terraform AWS"

on:
  push:
    branches:
      - main

env:
  TERRAFORM_DIR: ./terraform/aws

permissions:
  id-token: write # Required for requesting the JWT
  contents: read # Required for actions/checkout

jobs:
  terraform:
    name: apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set up AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-actions
          aws-region: ap-northeast-1

      - name: terraform init
        run: terraform init
        working-directory: ${{ env.TERRAFORM_DIR }}

      - name: terraform fmt
        run: terraform fmt -check
        working-directory: ${{ env.TERRAFORM_DIR }}

      - name: terraform apply
        run: terraform apply --auto-approve
        working-directory: ${{ env.TERRAFORM_DIR }}
